Tas 19 create a login fields
Agile-Build-Delivery/TaskMuse pull request #8
Opened 2023-11-09 19:45 UTC by psavarmattas

- Login Page Implementation.
- Sign Up Page layout correction.
- Forget Password button right now redirects to Sign up page and will be change to redirect to Forget Password page when completed.
- On successful login right now redirects to Sign up page and will be change to redirect to Main dashboard page when completed.
- On successful signup right now redirects to Login in page and will be change to redirect to Get Started page when completed.

2023-11-09 23:00 UTC, sandeshkulk approved these changes

2023-11-10 20:11 UTC, Agata-Duda requested changes

2023-11-10 20:17 UTC, psavarmattas commented on app/build.gradle.kts
>      namespace = "com.taskmuse.app"
Removed!

2023-11-10 20:17 UTC, psavarmattas commented on app/build.gradle.kts
>          applicationId = "com.taskmuse.app"
Removed!

2023-11-10 20:19 UTC, Agata-Duda approved these changes

2023-11-10 20:23 UTC, merged